# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kevin Vo
title: Software Development Engineer - Intern
email: me@kevinkvo.com
# website: kevinkvo.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  kevin-k-vo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kevin-vo-60b7b220a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links

# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg

about_content: | # this will include new lines to allow paragraphs
  My name is Kevin Vo and I am currently a student pursuing a Bachelor of Science in Computer Science at Oregon State University and an incoming software development intern at Amazon for Summer 2022.
  
  <mark>Languages:</mark> C/C++, Python, Java, JavaScript, HTML, CSS, SQL
  
  <mark>Technologies:</mark> Flask, Node.js, Express.js, MySQL, Git, Google Cloud Platform
  
  Possess a strong foundation in object-oriented programming, data structures, and algorithms
  
  <mark>Familiar with:</mark> computer networking fundamentals, relational and non-relational databases, version control (Git), cloud computing services (Google Cloud Platform), REST APIs, Docker, software testing, operating systems, software development life cycle (SDLC), UNIX, Linux



content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amazon
        link: Amazon.com
        # link_text: boringcompany.com
        sub_title: Software Development Engineer - Intern
        caption: June 2022 - Present
        quote: >
           “Work Hard. Have Fun. Make History.”
        description: | # this will include new lines to allow paragraphs
          - Collaborate with experienced cross-disciplinary Amazonians to conceive, design, and bring innovative products and services to market.
          - Design and build innovative technologies in a large distributed computing environment, and help lead fundamental changes in the industry.
          - Create solutions to run predictions on distributed systems with exposure to innovative technologies at incredible scale and speed.
          - Build distributed storage, index, and query systems that are scalable, fault-tolerant, low cost, and easy to manage/use.
          - Ability to design and code the right solutions starting with broadly defined problems.
          - Work in an agile environment to deliver high-quality software.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Oregon State University  
        caption: Graduating 2022
        sub_title: B.S. Computer Science
        quote: >
          Oregon State University is an international public research university that works to address global issues like climate change, health and wellness, food supply, renewable energy and advanced technology in one of the safest, smartest and greenest small cities in the nation.
        description: | # this will include new lines to allow paragraphs
          Relevant Coursework: Web Development, Data Structures, Introduction to Databases, Analysis of Algorithms, Introduction to Computer Networks, Cloud Application Development, Introduction to Software Testing

          Coursework In-Progress: Introduction to Operating Systems, Introduction to Software Development Life-Cycle


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: To-Do List
        link: github.com/kevin-k-vo/to-do-list
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A JavaScript web application that allows user to create, read, update, and delete tasks.
        description: | # this will include new lines to allow paragraphs
          - This project was a way for me to learn web development from a full-stack perspective.
          - Front-end: JavaScript, HTML, & CSS
          - Back-end: JavaScript, Node.js, Express.js, & SQLite

      - layout: top-middle
        title: Setlist to Spotify
        link: github.com/kevin-k-vo/setlist-to-spotify
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A Python script that takes a DJ’s live setlist and creates a playlist on Spotify with the retrieved data.
        description: | # this will include new lines to allow paragraphs
          - During the completion of this project, I learned about web scraping and how to interact with APIs.
          - Language used: Python
  



  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
